version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "08:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: serverless
    versions:
    - 2.21.1
    - 2.22.0
    - 2.23.0
    - 2.25.1
    - 2.25.2
    - 2.27.0
    - 2.27.1
    - 2.28.0
    - 2.28.3
    - 2.28.6
    - 2.28.7
    - 2.29.0
    - 2.30.3
    - 2.31.0
    - 2.32.0
    - 2.32.1
    - 2.33.1
    - 2.34.0
    - 2.37.1
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: "@types/jest"
    versions:
    - 26.0.20
    - 26.0.21
    - 26.0.22
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.12.11
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.0
    - 7.13.10
    - 7.13.12
    - 7.13.5
    - 7.13.8
    - 7.13.9
  - dependency-name: eslint-plugin-prettier
    versions:
    - 3.3.1
  - dependency-name: serverless-offline
    versions:
    - 6.8.0
  - dependency-name: jsdoc
    versions:
    - 3.6.6
  - dependency-name: http-proxy
    versions:
    - 1.18.1
  - dependency-name: elliptic
    versions:
    - 6.5.3
